### ISSUE TITLE
Abusing of toxme list

### ISSUE THREAD

**Issue by ghost** [LittleVulpix/toxme#20]
I don't know for what purposes toxme was originally created. But it is abused by some full idiots. 

There are some idiots that abusing tox (exactly the list from toxme.io) for sex-chats and other strange purposes. 
They write to everyone who is new at the list.

Maybe you can reproduce this if you publish your toxid to the list, and after a short time many idiots writing to you for sex and other strange purposes.

The id should be per default hidden from public list to prevent this.

**Comment by Monsterovich** [comment]
+1

**Comment by LittleVulpix** [comment]
Not sure how I missed this issue; but yeah. I'll have a look into this. I'm contemplating just getting rid of the browse functionality altogether, that's not what toxme is used for after all. It should be more of a just "DNS" server without the whole social aspect. You will still be able to query someone's name and see all of their details - but only on a per-lookup basis.

**Comment by LittleVulpix** [comment]
@Monsterovich , @solkgts , see for yourself. If more needs to be done, let me know, but I think this is fine.
