### ISSUE TITLE
[Enquiry] Is it possible to lookup parts of the bio?

### ISSUE THREAD

**Issue by lf-araujo** [LittleVulpix/toxme#21]
I am creating a piece of software to allow users to blindly peer-review scientific texts and was considering using toxme. The way I envisioned it, the user would add hashtags with their expertise, like for example `#multivariate-statistics` and my software would send this user the contents of a text without its original author's name, and so on.

Is it possible to lookup the bio for hashtags? I can't find how to do it in the API description.

Thank you

**Comment by LittleVulpix** [comment]
Hello,

It is not possible to look up by bio; the field is not indexed or exposed other than when you query user's details.

**Comment by lf-araujo** [comment]
thank you!
