### ISSUE TITLE
Associating toxme.io profile with a different Tox ID

### ISSUE THREAD

**Issue by Zenexer** [LittleVulpix/toxme#23]
I registered on toxme.io ages ago as `zenexer@toxme.io`.  I doubt I still have access to the Tox ID on there (`6EB0EE83A9D123E4A71E9525CBFFEF957D789D99415C29A7E6F8C3F9DDDC324AE5F036898DA3`).  However, I do have a password recorded in my password manager for toxme.io.  It's comprised of groups of three lowercase letters separated by hyphens.  It doesn't look like something I would've generated myself, so I assume it's some sort of recovery key.  Is it possible to use it to associate my toxme.io entry with a different Tox ID (or, even better, multiple IDs)?

**Comment by LittleVulpix** [comment]
Certainly. To change anything about your toxme.io account, all you need is the password and the name of the account. You can delete, add or change any details related to your account as long as you have the two. It is not possible to associate one account with multiple IDs as Tox does not support such feature itself and some clients use toxme.io to resolve addresses.

Anyway, to change everything, all you need to do is go here:

https://toxme.io/edit_ui

And put in your username (without @toxme.io, so just "zenexer"), your password - and then either put in a new Tox ID and use the "update" button - or hit the delete button (which does not require any other ID, just name+pw) and that will work.

Let me know if you still have issues.

**Comment by Zenexer** [comment]
Thanks!
